on:
  schedule:
    - cron:  '0 3 * * *'
  workflow_dispatch:

jobs:
  generate-gif:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: get the png from the start of the current year
        run: |
          dfrom=$(date +%Y-01-01)
          d=$(date +%Y-01-01)
          while [ "$d" != "$(date +%Y-%m-%d)" ] #loop until today - 1 
          do
            png=graph-$d.png
            if [[ -e png/$png ]] #don't redownload already saved dates
            then
              echo "$png already downloaded"
            else
              echo -n "downloading $png.." && curl --silent https://atuin.bluegreen.sh/graph/tieum/$dfrom/$d --output png/$png && \
              [[ ! -s png/$png ]] && (echo "empty file, deleting" && rm png/$png) || echo downloaded
            fi
            d=$(date -I -d "$d + 1 day")
          done
      - name: make a gif from the pngs
        id: convert
        continue-on-error: true
        run: |
          if [[ -n $(git status --porcelain) ]] #no point wasting cpu if nothing changed
          then
            convert -delay 10 -loop 1 png/*.png shell.history.gif
          else
            exit 1
          fi
      - name: save new pngs & resulting gif
        if: steps.convert.outcome== 'success'
        run: |
          git config --global user.name 'tieum'
          git config --global user.email 'tieum@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add png/*.png
          git commit -am "[auto] update shell.history.gif"
          git push
